services:
  backend:
    container_name: nodeherder-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4100:4100"
    environment:
      APP_ENV: production
      MQTT_URL: tcp://192.168.50.241:1883
