services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nodeherder-frontend
    ports:
      - "4100:80" # DEBUG - change to 80:80
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
