export enum RouteName {
  Login = 'login',
  Overview = 'overview',
  Panel = 'panel',
  Devices = 'devices',
  GroupDashboard = 'groupdashboard',
  DeviceList = 'devicelist',
  Viewer = 'viewer',
  Settings = 'settings',
  ConsoleViewer = 'consoleviewer',
  Creator = 'creator',
  Editor = 'editor',
  DevicePage = 'devicepage',
  DeviceView = 'deviceview',
  Assistant = 'assistant',
}
